import * as React from "react";
import { Link } from "react-router-dom";
import { PageTransition } from "../components/ui/PageTransition";
import { Card } from "../components/ui/Card";
import { Button } from "../components/ui/Button";
import { ArrowLeft } from "lucide-react";

export function TermsAndConditions() {
  return (
    <PageTransition className="pb-24">
      <div className="mx-auto max-w-4xl px-4 py-12">
        {/* Header */}
        <div className="mb-8 flex items-center gap-3">
          <Link to="/signup">
            <Button variant="ghost" size="icon">
              <ArrowLeft className="h-5 w-5" />
            </Button>
          </Link>
          <div>
            <h1 className="text-2xl font-bold tracking-tight">
              Terms & Conditions
            </h1>
            <p className="text-sm text-foreground-muted">
              Please read these terms carefully before using DigiLab
            </p>
          </div>
        </div>

        <Card className="p-8 space-y-8">
          {/* Meta */}
          <p className="text-sm text-foreground-muted">
            <strong>Last Updated:</strong>{" "}
            {new Date().toLocaleDateString()}
          </p>

          {/* Introduction */}
          <section className="space-y-3">
            <p className="text-sm leading-relaxed">
              Welcome to <strong>DigiLab</strong> ("Platform", "we", "our", or
              "us"). These Terms and Conditions govern your access to and use of
              our AI-powered academic assistance platform. By accessing or
              using DigiLab, you agree to be legally bound by these terms.
            </p>

            <p className="text-sm leading-relaxed">
              If you do not agree with any part of these Terms, you must
              discontinue use of the platform immediately.
            </p>
          </section>

          {/* 1 */}
          <section className="space-y-2">
            <h2 className="text-lg font-semibold">
              1. Acceptance of Terms
            </h2>
            <p className="text-sm leading-relaxed">
              By creating an account, accessing, or using DigiLab, you confirm
              that you have read, understood, and agreed to these Terms and
              Conditions and any related policies referenced herein.
            </p>
          </section>

          {/* 2 */}
          <section className="space-y-2">
            <h2 className="text-lg font-semibold">
              2. Use of the Platform
            </h2>
            <ul className="list-disc pl-6 text-sm space-y-1 leading-relaxed">
              <li>
                DigiLab is intended solely for educational and academic support
                purposes.
              </li>
              <li>
                You agree not to misuse the platform, interfere with system
                operations, or attempt unauthorized access.
              </li>
              <li>
                You are responsible for maintaining the confidentiality of your
                account credentials.
              </li>
            </ul>
          </section>

          {/* 3 */}
          <section className="space-y-2">
            <h2 className="text-lg font-semibold">
              3. User Conduct & Responsibilities
            </h2>
            <p className="text-sm leading-relaxed">
              You agree not to submit, upload, or share content that is
              unlawful, harmful, misleading, abusive, defamatory, or violates
              intellectual property or privacy rights of others.
            </p>
          </section>

          {/* 4 */}
          <section className="space-y-2">
            <h2 className="text-lg font-semibold">
              4. AI-Generated Content Disclaimer
            </h2>
            <p className="text-sm leading-relaxed">
              Content generated by DigiLab is provided for informational and
              guidance purposes only. We do not guarantee accuracy,
              completeness, or suitability for academic submission, exams, or
              professional use. Users are advised to verify information
              independently.
            </p>
          </section>

          {/* 5 */}
          <section className="space-y-2">
            <h2 className="text-lg font-semibold">
              5. Privacy & Data Protection
            </h2>
            <p className="text-sm leading-relaxed">
              Your privacy is important to us. Personal data is collected and
              processed in accordance with our Privacy Policy. By using DigiLab,
              you consent to such collection and use.
            </p>
          </section>

          {/* 6 */}
          <section className="space-y-2">
            <h2 className="text-lg font-semibold">
              6. Limitation of Liability
            </h2>
            <p className="text-sm leading-relaxed">
              To the maximum extent permitted by law, DigiLab shall not be liable
              for any indirect, incidental, consequential, or special damages
              arising from your use of or inability to use the platform.
            </p>
          </section>

          {/* 7 */}
          <section className="space-y-2">
            <h2 className="text-lg font-semibold">
              7. Modifications to Terms
            </h2>
            <p className="text-sm leading-relaxed">
              We reserve the right to modify or update these Terms at any time.
              Continued use of the platform following changes constitutes your
              acceptance of the revised Terms.
            </p>
          </section>

          {/* 8 */}
          <section className="space-y-2">
            <h2 className="text-lg font-semibold">
              8. Contact Information
            </h2>
            <p className="text-sm leading-relaxed">
              If you have any questions or concerns regarding these Terms and
              Conditions, please contact us through the official support
              channels provided within the platform.
            </p>
          </section>

        </Card>
      </div>
    </PageTransition>
  );
}
